### ISSUE TITLE
Says Card Numbers with Too Few Digits are Valid

### ISSUE THREAD

**Issue by DaveBatton** [vitkuzmenko/CreditCardValidator#12]
The app example app says that this is a valid Visa card number: **4242424242**

All of the sources I can find say a Visa card must have 13, 16, or 19 characters. That number has 10 digits. Are you certain this is correct?

**Comment by ghost** [comment]
I see that in the library we don't check against valid number length given by each C/C provider.
I'm preparing a pull request to fix this.

**Comment by ghost** [comment]
@vitkuzmenko PR opened for that issue: https://github.com/vitkuzmenko/CreditCardValidator/pull/19

**Comment by vitkuzmenko** [comment]
@DaveBatton check it in `0.5.3` with @fredadda-fiverr fixes
