### ISSUE TITLE
The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by HemanthRamapuram1995** [vitkuzmenko/CreditCardValidator#17]
IDE Xcode 13 
library version 0.5.1

The creditcardvalidator library is not compiling
<img width="1452" alt="Screenshot 2021-09-22 at 11 46 42 AM" src="https://user-images.githubusercontent.com/91176532/134292565-e30a9453-8f1b-431c-858f-84af24e17032.png">

**Comment by stevenbenitez** [comment]
I'm having the same issue.

**Comment by teodortalov** [comment]
@HemanthRamapuram1995 @stevenbenitez we have created a PR that addresses this issue, I hope @vitkuzmenko can merge it soon so that we can all move on :)

**Comment by ghost** [comment]
Great job! I hope it will be merged soon @vitkuzmenko

**Comment by vitkuzmenko** [comment]
Thanks. Merged.
